hash-format = "sha256"

[[files]]
file = "config/moderate-loading-screen.json5"

[[files]]
file = "config/styled-chat.json"

[[files]]
file = "mods/HexVR-1.5.2 [FABRIC 1.20.1].jar"

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/caduceus-fabric-0.1.1+1.20.1.jar"

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/complexhex-fabric-1.20.1-0.1.3-beta.jar"

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
metafile = true

[[files]]
file = "mods/efhexs-1.0.0.jar"

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/ephemera-fabric-1.20.1-0.3.0.jar"

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrication.pw.toml"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/gravity-changer-1.1.2+mc1.20.1.jar"

[[files]]
file = "mods/helpfromhexxy-fabric-1.20.1-0.1.4.jar"

[[files]]
file = "mods/hex_machina-1.0.1.jar"

[[files]]
file = "mods/hexal-fabric-1.20.1-0.3.0-3-skyevg-unofficial-teleport-experiment.jar"

[[files]]
file = "mods/hexcassettes-1.1.4.jar"

[[files]]
file = "mods/hexcasting-fabric-1.20.1-0.11.2.3-SpellCircle.jar"

[[files]]
file = "mods/hexcellular-1.1.0.jar"

[[files]]
file = "mods/hexchanting-1.1.3.jar"

[[files]]
file = "mods/hexdebug-fabric-0.3.0+1.20.1.jar"

[[files]]
file = "mods/hexical-2.0.0.jar"

[[files]]
file = "mods/hexlands.pw.toml"
metafile = true

[[files]]
file = "mods/hexodus-1.0.0.jar"

[[files]]
file = "mods/hexpats-0.1.1-1.20.1.jar"

[[files]]
file = "mods/hexportation-fabric-1.20.1-0.0.1.jar"

[[files]]
file = "mods/hexpose-1.0.0.jar"

[[files]]
file = "mods/hexstruction-fabric-1.2.1+1.20.1.jar"

[[files]]
file = "mods/hierophantics.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-optimization.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
metafile = true

[[files]]
file = "mods/ioticblocks-fabric-1.0.1+1.20.1.jar"

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jline4mcdsrv.pw.toml"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/lanishextendedstaves-1.20.1-1.0.1.jar"

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lmft.pw.toml"
metafile = true

[[files]]
file = "mods/moderate-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/moreiotas-fabric-1.20.1-0.1.0-5.jar"

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/movesthemind-1.0.3.jar"

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/notes.pw.toml"
metafile = true

[[files]]
file = "mods/oneironaut-fabric-1.20.1-0.5.0.jar"

[[files]]
file = "mods/overevaluate-1.0.0.jar"

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/phlexiful-fabric-1.0.0.jar"

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/scryglass-1.0.0.jar"

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/servertick.pw.toml"
metafile = true

[[files]]
file = "mods/slate_work-0.1.1.jar"

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
metafile = true
